#Datasource Configuration
#spring.datasource.hikari.maximum-pool-size=4
#spring.datasource.url=jdbc:postgresql://localhost:5432/devops
#spring.datasource.username=admin
#spring.datasource.password=admin
#spring.sql.init.platform=datasource.platform=devops


server:
  port: 8080

spring:

  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.10.2:2866/postgre
    username: admin
    password: admin123!
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
     hibernate:
      format_sql: true
  sql:
    init:
      platform: postgres